# Generated by Django 5.2.11 on 2026-03-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_membershiprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='member_id',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
