# Generated by Django 5.2.11 on 2026-03-01 08:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_membership_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_id',
            field=models.CharField(default=api.models.generate_unique_member_id, editable=False, max_length=3, unique=True),
        ),
    ]
