# Generated by Django 5.2.11 on 2026-03-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_productrestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=10),
        ),
    ]
