# Generated by Django 5.2.11 on 2026-03-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productsale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.worker'),
        ),
    ]
