# Generated by Django 5.2.11 on 2026-03-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
