# Generated by Django 5.2.11 on 2026-03-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_membership_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
