# Generated by Django 5.2.11 on 2026-03-09 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_membershiprecord_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='api.transaction'),
        ),
        migrations.AddField(
            model_name='membershiprecord',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_record', to='api.transaction'),
        ),
    ]
