# Generated by Django 5.2.11 on 2026-03-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('leave', 'Leave/Holiday')], default='present', max_length=20),
        ),
    ]
