# Generated by Django 5.2.11 on 2026-05-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_amount', models.DecimalField(decimal_places=2, default=25000.0, max_digits=10)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
    ]
