# Generated by Django 5.2.11 on 2026-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_renttarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='renttarget',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
