# Generated by Django 5.2.11 on 2026-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
    ]
